module.exports = {
  'afghanistan': 'AF',
  'afrique du sud': 'ZA',
  'aland': 'AX',
  'albanie': 'AL',
  'algerie': 'DZ',
  'allemagne': 'DE',
  'andorre': 'AD',
  'angola': 'AO',
  'anguilla': 'AI',
  'antarctique': 'AQ',
  'antigua et barbuda': 'AG',
  'arabie saoudite': 'SA',
  'argentine': 'AR',
  'armenie': 'AM',
  'aruba': 'AW',
  'australie': 'AU',
  'autriche': 'AT',
  'azerbaidjan': 'AZ',
  'bahamas': 'BS',
  'bahrein': 'BH',
  'bangladesh': 'BD',
  'barbade': 'BB',
  'belarus': 'BY',
  'belgique': 'BE',
  'belize': 'BZ',
  'benin': 'BJ',
  'bermudes': 'BM',
  'bhoutan': 'BT',
  'bolivie': 'BO',
  'bonaire': 'BQ',
  'bosnie-herzegovine': 'BA',
  'botswana': 'BW',
  'bouvet': 'BV',
  'bresil': 'BR',
  'brunei darussalam': 'BN',
  'bulgarie': 'BG',
  'burkina faso': 'BF',
  'burundi': 'BI',
  'caimanes': 'KY',
  'cambodge': 'KH',
  'cameroun': 'CM',
  'canada': 'CA',
  'cap-vert': 'CV',
  'centrafricaine': 'CF',
  'chili': 'CL',
  'chine': 'CN',
  'christmas': 'CX',
  'chypre': 'CY',
  'cocos': 'CC',
  'colombie': 'CO',
  'comores': 'KM',
  'congo': 'CG',
  'cook': 'CK',
  'coree': 'KR',
  'costa rica': 'CR',
  'cote d\'ivoire': 'CI',
  'croatie': 'HR',
  'cuba': 'CU',
  'curacao': 'CW',
  'danemark': 'DK',
  'djibouti': 'DJ',
  'dominicaine': 'DO',
  'dominique': 'DM',
  'egypte': 'EG',
  'el salvador': 'SV',
  'emirats arabes unis': 'AE',
  'equateur': 'EC',
  'erythree': 'ER',
  'espagne': 'ES',
  'estonie': 'EE',
  'etats-unis': 'US',
  'ethiopie': 'ET',
  'falkland': 'FK',
  'feroe': 'FO',
  'fidji': 'FJ',
  'finlande': 'FI',
  'france': 'FR',
  'gabon': 'GA',
  'gambie': 'GM',
  'georgie': 'GE',
  'georgie du sud et les iles sandwich du sud': 'GS',
  'ghana': 'GH',
  'gibraltar': 'GI',
  'grece': 'GR',
  'grenade': 'GD',
  'groenland': 'GL',
  'guadeloupe': 'GP',
  'guam': 'GU',
  'guatemala': 'GT',
  'guernesey': 'GG',
  'guinee': 'GN',
  'guinee-bissau': 'GW',
  'guinee equatoriale': 'GQ',
  'guyana': 'GY',
  'guyane francaise': 'GF',
  'haiti': 'HT',
  'heard': 'HM',
  'honduras': 'HN',
  'hong kong': 'HK',
  'hongrie': 'HU',
  'ile de man': 'IM',
  'iles mineures eloignees des etats-unis': 'UM',
  'iles vierges britanniques': 'VG',
  'iles vierges des etats-unis': 'VI',
  'inde': 'IN',
  'indonesie': 'ID',
  'iran': 'IR',
  'iraq': 'IQ',
  'irlande': 'IE',
  'islande': 'IS',
  'israel': 'IL',
  'italie': 'IT',
  'jamaique': 'JM',
  'japon': 'JP',
  'jersey': 'JE',
  'jordanie': 'JO',
  'kazakhstan': 'KZ',
  'kenya': 'KE',
  'kirghizistan': 'KG',
  'kiribati': 'KI',
  'koweit': 'KW',
  'lao': 'LA',
  'lesotho': 'LS',
  'lettonie': 'LV',
  'liban': 'LB',
  'liberia': 'LR',
  'libyenne': 'LY',
  'liechtenstein': 'LI',
  'lituanie': 'LT',
  'luxembourg': 'LU',
  'm': 'LU',
  'macao': 'MO',
  'macedoine': 'MK',
  'madagascar': 'MG',
  'malaisie': 'MY',
  'malawi': 'MW',
  'maldives': 'MV',
  'mali': 'ML',
  'malte': 'MT',
  'mariannes du nord': 'MP',
  'maroc': 'MA',
  'marshall': 'MH',
  'martinique': 'MQ',
  'maurice': 'MU',
  'mauritanie': 'MR',
  'mayotte': 'YT',
  'mexique': 'MX',
  'micronesie': 'FM',
  'moldova': 'MD',
  'monaco': 'MC',
  'mongolie': 'MN',
  'montenegro': 'ME',
  'montserrat': 'MS',
  'mozambique': 'MZ',
  'myanmar': 'MM',
  'namibie': 'NA',
  'nauru': 'NR',
  'nepal': 'NP',
  'nicaragua': 'NI',
  'niger': 'NE',
  'nigeria': 'NG',
  'niue': 'NU',
  'norfolk': 'NF',
  'norvege': 'NO',
  'nouvelle-caledonie': 'NC',
  'nouvelle-zelande': 'NZ',
  'ocean indien': 'IO',
  'oman': 'OM',
  'ouganda': 'UG',
  'ouzbekistan': 'UZ',
  'pakistan': 'PK',
  'palaos': 'PW',
  'palestinien occupe': 'PS',
  'panama': 'PA',
  'papouasie-nouvelle-guinee': 'PG',
  'paraguay': 'PY',
  'pays-bas': 'NL',
  'perou': 'PE',
  'philippines': 'PH',
  'pitcairn': 'PN',
  'pologne': 'PL',
  'polynesie francaise': 'PF',
  'porto rico': 'PR',
  'portugal': 'PT',
  'qatar': 'QA',
  'reunion': 'RE',
  'roumanie': 'RO',
  'royaume-uni': 'GB',
  'russie': 'RU',
  'rwanda': 'RW',
  'sahara occidental': 'EH',
  'saint-barthelemy': 'BL',
  'sainte-helene': 'SH',
  'sainte-lucie': 'LC',
  'saint-kitts-et-nevis': 'KN',
  'saint-marin': 'SM',
  'saint-martin francaise': 'MF',
  'saint-martin neerlandaise': 'SX',
  'saint-pierre-et-miquelon': 'PM',
  'saint-siege': 'VA',
  'saint-vincent-et-les grenadines': 'VC',
  'salomon': 'SB',
  'samoa': 'WS',
  'samoa americaines': 'AS',
  'sao tome-et-principe': 'ST',
  'senegal': 'SN',
  'serbie': 'RS',
  'seychelles': 'SC',
  'sierra leone': 'SL',
  'singapour': 'SG',
  'slovaquie': 'SK',
  'slovenie': 'SI',
  'somalie': 'SO',
  'soudan': 'SD',
  'sri lanka': 'LK',
  'suede': 'SE',
  'suisse': 'CH',
  'suriname': 'SR',
  'svalbard et ile jan mayen': 'SJ',
  'swaziland': 'SZ',
  'syrienne': 'SY',
  'tadjikistan': 'TJ',
  'taiwan': 'TW',
  'tanzanie': 'TZ',
  'tchad': 'TD',
  'tcheque': 'CZ',
  'terres australes francaises': 'TF',
  'thailande': 'TH',
  'timor-leste': 'TL',
  'togo': 'TG',
  'tokelau': 'TK',
  'tonga': 'TO',
  'trinite-et-tobago': 'TT',
  'tunisie': 'TN',
  'turkmenistan': 'TM',
  'turks et caiques': 'TC',
  'turquie': 'TR',
  'tuvalu': 'TV',
  'ukraine': 'UA',
  'uruguay': 'UY',
  'vanuatu': 'VU',
  'vatican': 'S E',
  'venezuela': 'VE',
  'viet nam': 'VN',
  'wallis et futuna': 'WF',
  'yemen': 'YE',
  'zambie': 'ZM',
  'zimbabwe': 'ZW',
}
