/* eslint-disable */
module.exports = [
  `quels sont vos horaires ?`,
  `Travaillez vous le samedi ?`,
  `Est-ce que je peux te contacter la nuit ?`,
  `Quand fermez vous`,
  `Tu peux me donner les horaires d'ouvertures d'EuropAssistance ?`,
  `horrair`,
  `Quels sont vos horaires d'ouverture ?`,
  `Êtes vous dispo`,
  `c'est quoi vos horaires`,
  `A quelle heure puis-je contacter votre service assistance ?`,
  `Travaillez-vous les jours fériés ?`,
  `A quelle heure est-ce que je peux vous contacter ?`,
  `Vous êtes ouverts en ce moment ?`,
  `Vous ētes ouverts en ce moment ?`,
  `Est-ce que vous ētes ouverts ?`,
  `A quel moment est-ce que je peux vous contacter ?`,
  `Quand est-ce que je peux vous contacter ?`,
  `A quelle heure est-ce que je peux vous contacter ?`,
  `A quelles heures est-ce que je peux vous joindre ?`,
  `Je cherche les horaires d'EuropAssistance`,
  `Est-ce que tu peux me renseigner sur les horaires ?`,
  `A quel moment est-ce que je peux vous appeler ?`,
  `A quelle heure est-ce que je peux vous appeler ?`,
  `Quels sont vos horaires ?`,
  `Est-ce que vous êtes ouverts pendant les vacances ?`,
  `Est-ce que vous êtes ouvert le week-end ?`,
  `Vous êtes ouvert le week-end ?`,
  `Est-ce que vous êtes ouverts les jours feriés ?`,
  `Tu peux me donner les horaires d'ouvertures d'EuropAssistance ?`,
  `Je cherche vos horaires d'ouverture`,
  `Quand est-ce que je peux vous joindre ?`,
  `Est-ce que votre service d'assistance est joignable pendant cette semaine ?`,
  `Est-ce que votre service d'assistance est joignable pendant les vacances ?`,
  `Est-ce que votre service d'assistance est joignable le week-end ?`,
  `Vous êtes ouvert aujourd'hui ?`,
  `et vos horaires d'ouverture ?`,
  `horaires d'ouverture`,
  `horaires d'ouverture stp`,
  `Travaillez vous les jours fériés ?`,
  `a quelle heure vous contacter pour acheter un contrat`,
  `Quand puis je vous appeler pour souscrire à un contrat`,
  `Travaillez vous le samedi ?`,
  `Travaillez vous les jours férié`,
  `Travaillez vous le lundi de Pentecôte ?`,
  `Pourriez vous m'appeler ?`,
  `je peux vous contacter quelle heure`,
  `dispo 23h ?`,
  `travaillez 00h ?`,
  `horaire`,
  `Horaire`,
  `quelle heure téléphoner`,
  `quelle heure téléphon`,
  `Quand je peux vous appeler pour acheter une assurance`,
  `Quand fermez vous`,
  `Sur quel horaire intervenez vous`,
  `Quand est-ce que je peux vous téléphoner ?`,
  `A quel moment est-ce que je peux vous appeler ?`,
  `Quand vous appelez ?`,
  `Je peux vous appeler maintenant ?`,
  `horaires plateaux`,
  `Horaires plateaux`,
  `Horaires du plateaux`,
  `les horaires plateaux`,
  `Les horaires du plateaux`,
]
